mode = "light"

accent = "#3B5E85"
selection = "#B8C2CF"
muted = "#526074"

background = "#D8DEE9"
dark_background = "#C8D0DA"
darker_background = "#B8C2CF"
lighter_background = "#E5E9F0"

foreground = "#2E3440"
dark_foreground = "#526074"
light_foreground = "#3B4252"
bright_foreground = "#2E3440"

red = "#A2424A"
yellow = "#755E12"
orange = "#8B523E"
green = "#50683B"
cyan = "#0B6B78"
blue = "#3B5E85"
magenta = "#7B5475"
brown = "#6A4B3D"

bright_red = "#A2424A"
bright_yellow = "#755E12"
bright_green = "#50683B"
bright_cyan = "#1A6C6B"
bright_blue = "#466482"
bright_magenta = "#7B5475"
